# Generated by Django 2.1.1 on 2019-06-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190614_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
