# Generated by Django 2.1.1 on 2019-05-07 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsn_name', models.CharField(max_length=50)),
                ('db_host', models.CharField(default='127.0.0.1', max_length=100)),
                ('db_user', models.CharField(max_length=50)),
                ('db_pw', models.CharField(max_length=50)),
                ('db_name', models.CharField(default='test_db', max_length=50)),
                ('db_type', models.CharField(choices=[('oracle', 'oracle'), ('sqlserver', 'sqlserver'), ('teradata', 'teradata'), ('mysql', 'mysql')], default='oracle', max_length=25)),
                ('db_param', models.CharField(blank=True, max_length=100)),
                ('db_port_no', models.IntegerField(default=0, max_length=6)),
                ('dsn_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Env_variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_variable_name', models.CharField(max_length=100)),
                ('env_variable_value', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='InitialTbllist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_names', models.CharField(default='', max_length=100)),
                ('table_type', models.CharField(default='T', max_length=1)),
                ('is_selected', models.BooleanField(default=False)),
                ('dsn_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('hdfs_dir', models.CharField(default='/home/rawdata/', max_length=1000)),
                ('email_notification', models.CharField(default='arjun.kumar@kp.org', max_length=100)),
                ('etl_sch_time', models.CharField(default='', max_length=50)),
                ('is_active', models.CharField(default='Y', max_length=1)),
                ('max_num_of_threads', models.SmallIntegerField(default=5)),
                ('sch_indicator', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report_monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(default='', max_length=200)),
                ('procedure_name', models.CharField(default='', max_length=50)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('end_time', models.CharField(default='NA', max_length=50)),
                ('process_time', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='', max_length=50)),
                ('remark', models.CharField(default='', max_length=100)),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Spname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=100)),
                ('sp_name', models.CharField(max_length=100)),
                ('start_dt', models.CharField(blank=True, default='NULL', max_length=50)),
                ('end_dt', models.CharField(blank=True, default='NULL', max_length=50)),
                ('med_center', models.CharField(blank=True, default='NULL', max_length=100)),
                ('result_table', models.CharField(max_length=50)),
                ('additional_param', models.CharField(blank=True, default='NULL', max_length=400)),
                ('etl_sch_time', models.CharField(blank=True, default='', max_length=50)),
                ('priority_id', models.SmallIntegerField(default=1, max_length=1)),
                ('execution_flag', models.CharField(default='Y', max_length=1)),
                ('dsn_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.DataSource')),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Project')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tbllist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('result_table', models.CharField(max_length=100)),
                ('table_type', models.CharField(default='T', max_length=1)),
                ('priority_id', models.SmallIntegerField(default=1, max_length=1)),
                ('import_utility', models.CharField(default='sqoop', max_length=50)),
                ('custom_cmd', models.CharField(blank=True, max_length=500)),
                ('additional_param', models.CharField(blank=True, max_length=400)),
                ('etl_sch_time', models.CharField(max_length=100)),
                ('execution_flag', models.CharField(default='Y', max_length=1)),
                ('dsn_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.DataSource')),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Project')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='initialtbllist',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Project'),
        ),
        migrations.AddField(
            model_name='initialtbllist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='env_variables',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Project'),
        ),
        migrations.AddField(
            model_name='env_variables',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Project'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
