# Generated by Django 2.1.1 on 2019-05-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
