# Generated by Django 2.1.1 on 2019-05-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0005_artist_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
