# Generated by Django 2.1.1 on 2019-05-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0007_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
