# Generated by Django 2.1.1 on 2019-05-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0009_auto_20190509_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
