# Generated by Django 2.1.1 on 2019-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0012_project_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_access',
            name='justification',
            field=models.CharField(default='Need access to the project to make change and execute jobs', max_length=500),
        ),
    ]
