# Generated by Django 2.1.1 on 2019-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0013_project_access_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_access',
            name='status',
            field=models.CharField(default='access submited', max_length=50),
        ),
    ]
