# Generated by Django 2.1.1 on 2019-07-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0014_project_access_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_access',
            name='status',
        ),
    ]
