# Generated by Django 2.1.1 on 2019-07-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0015_remove_project_access_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_access',
            name='status',
            field=models.CharField(default='Access Submited', max_length=50),
        ),
    ]
