# Generated by Django 2.1.1 on 2019-07-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0018_auto_20190717_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_access',
            name='justification',
            field=models.CharField(default='Need access to the project to make change and execute jobs', max_length=100),
        ),
    ]
