# Generated by Django 2.1.1 on 2019-07-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0020_project_access_change_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_access',
            name='change_role',
        ),
        migrations.AlterField(
            model_name='project_access',
            name='role',
            field=models.CharField(choices=[('Master', 'Master: Full Access'), ('Developer', 'Developer: Add/Edit jobs'), ('Operator', 'Operator:Only Execute jobs')], default='Master', max_length=10),
        ),
    ]
