# Generated by Django 2.1.1 on 2019-07-21 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0022_auto_20190721_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.CharField(default='Need access to the project to make change and execute jobs', max_length=100)),
                ('role', models.CharField(choices=[('Master', 'Master: Full Access'), ('Developer', 'Developer: Add/Edit jobs'), ('Operator', 'Operator:Only Execute jobs')], default='Master', max_length=10)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('access', models.BooleanField(default=False)),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Project')),
                ('project_owner_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
