# Generated by Django 2.1.1 on 2019-07-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0023_project_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_access',
            old_name='justification',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='project_access',
            old_name='project_owner_id',
            new_name='project_owner',
        ),
        migrations.RenameField(
            model_name='project_access',
            old_name='user',
            new_name='requester',
        ),
    ]
