# Generated by Django 2.1.1 on 2019-07-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0025_auto_20190721_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_access',
            name='project_owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project_access',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
