# Generated by Django 2.1.1 on 2019-07-25 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0028_auto_20190725_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('script_path_name', models.CharField(max_length=200)),
                ('additional_param', models.CharField(max_length=300)),
                ('priority_id', models.SmallIntegerField(default=1, max_length=1)),
                ('etl_sch_time', models.CharField(max_length=100)),
                ('execution_flag', models.CharField(default='Y', max_length=1)),
                ('project_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Project')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
