# Generated by Django 2.1.1 on 2019-07-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0029_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='job_type',
            field=models.CharField(choices=[('oracle', 'oracle'), ('sqlserver', 'sqlserver'), ('teradata', 'teradata'), ('mysql', 'mysql')], default='Shell_Script', max_length=25),
        ),
        migrations.AddField(
            model_name='spname',
            name='job_type',
            field=models.CharField(choices=[('oracle', 'oracle'), ('sqlserver', 'sqlserver'), ('teradata', 'teradata'), ('mysql', 'mysql')], default='Stored_Proc', max_length=25),
        ),
        migrations.AddField(
            model_name='tbllist',
            name='job_type',
            field=models.CharField(choices=[('oracle', 'oracle'), ('sqlserver', 'sqlserver'), ('teradata', 'teradata'), ('mysql', 'mysql')], default='Table', max_length=25),
        ),
    ]
