# Generated by Django 2.1.1 on 2019-07-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0031_jobflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobflow',
            name='etl_sch_time',
            field=models.CharField(blank=True, default='job_name', max_length=100),
        ),
        migrations.AddField(
            model_name='jobflow',
            name='execution_flag',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='jobflow',
            name='job_name',
            field=models.CharField(default='job_name', max_length=25),
        ),
        migrations.AddField(
            model_name='jobflow',
            name='job_type',
            field=models.CharField(default='Stored_Proc', max_length=25),
        ),
        migrations.AddField(
            model_name='jobflow',
            name='priority_id',
            field=models.SmallIntegerField(default=1, max_length=2),
        ),
    ]
