# Generated by Django 2.1.1 on 2019-07-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0032_auto_20190726_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobflow',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='jobflow',
            name='user',
        ),
        migrations.DeleteModel(
            name='Jobflow',
        ),
    ]
