# Generated by Django 2.1.1 on 2019-07-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0034_jobflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobflow',
            name='priority_id',
            field=models.SmallIntegerField(default=1),
        ),
    ]
