# Generated by Django 2.1.1 on 2019-07-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0036_auto_20190730_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='db_port_no',
            field=models.IntegerField(default=0),
        ),
    ]
