# Generated by Django 2.1.1 on 2019-07-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0037_auto_20190730_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobflow',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='jobflow',
            name='user',
        ),
        migrations.DeleteModel(
            name='Jobflow',
        ),
    ]
