# Generated by Django 2.1.1 on 2019-07-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0039_jobflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobflow',
            name='email_notification',
            field=models.CharField(default='arjun.kumar@kp.org', max_length=100),
        ),
        migrations.AddField(
            model_name='jobflow',
            name='etl_sch_time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobflow',
            name='max_num_of_threads',
            field=models.SmallIntegerField(default=5),
        ),
    ]
