# Generated by Django 2.1.1 on 2019-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0040_auto_20190730_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobflow',
            name='execution_flag',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
