# Generated by Django 2.1.1 on 2019-07-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0041_jobflow_execution_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobflowdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='job_name', max_length=25)),
                ('job_type', models.CharField(default='Stored_Proc', max_length=25)),
                ('object_id', models.IntegerField(default=1)),
                ('priority_id', models.SmallIntegerField(default=1)),
                ('jobflowname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Jobflow')),
            ],
        ),
    ]
