# Generated by Django 2.1.1 on 2019-07-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0042_jobflowdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='job_type',
            field=models.CharField(choices=[('Table', 'Table'), ('Stored_Proc', 'Stored_Proc'), ('Shell_Script', 'Shell_Script')], default='Shell_Script', max_length=25),
        ),
        migrations.AlterField(
            model_name='spname',
            name='job_type',
            field=models.CharField(choices=[('Table', 'Table'), ('Stored_Proc', 'Stored_Proc'), ('Shell_Script', 'Shell_Script')], default='Stored_Proc', max_length=25),
        ),
        migrations.AlterField(
            model_name='tbllist',
            name='job_type',
            field=models.CharField(choices=[('Table', 'Table'), ('Stored_Proc', 'Stored_Proc'), ('Shell_Script', 'Shell_Script')], default='Table', max_length=25),
        ),
    ]
