# Generated by Django 2.1.1 on 2019-08-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0043_auto_20190731_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobflowdetail',
            name='execution_flag',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
