# Generated by Django 2.1.1 on 2019-08-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0044_jobflowdetail_execution_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobflowdetail',
            name='etl_sch_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
