# Generated by Django 2.1.1 on 2019-08-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0048_spname_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbllist',
            name='is_active',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1),
        ),
    ]
