# Generated by Django 2.1.1 on 2019-08-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0050_auto_20190807_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobflow',
            name='is_active',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='jobflowdetail',
            name='is_active',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='Y', max_length=1),
        ),
    ]
