# Generated by Django 2.1.1 on 2019-08-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0051_auto_20190807_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobflow',
            name='execution_flag',
        ),
    ]
