# Generated by Django 2.1.1 on 2019-08-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0052_remove_jobflow_execution_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobflowdetail',
            name='execution_flag',
        ),
    ]
