# Generated by Django 2.1.1 on 2019-08-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0053_remove_jobflowdetail_execution_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbllist',
            name='execution_flag',
        ),
    ]
