# Generated by Django 2.1.1 on 2019-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0055_remove_spname_execution_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobflowdetail',
            name='additional_param',
            field=models.CharField(default='', max_length=300),
        ),
    ]
