# Generated by Django 2.1.1 on 2019-08-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0056_jobflowdetail_additional_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobflowdetail',
            name='job_name',
            field=models.CharField(default='job_name', max_length=50),
        ),
    ]
