# Generated by Django 2.1.1 on 2019-08-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0058_jobflowdetail_job_name_alias_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobflowdetail',
            name='job_name_alias_name',
            field=models.CharField(default='job_name_alias_name', max_length=50),
        ),
    ]
