# Generated by Django 2.1.1 on 2019-08-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0059_auto_20190810_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobflowdetail',
            old_name='job_name_alias_name',
            new_name='project_job_name',
        ),
    ]
