# Generated by Django 2.1.1 on 2019-08-28 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0061_auto_20190810_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_job_name', models.CharField(default='job_name_alias_name', max_length=50)),
                ('jobflowname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Jobflow')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
