# Generated by Django 2.1.1 on 2019-08-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0062_processlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='additional_param',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='processlog',
            name='job_name',
            field=models.CharField(default='job_name', max_length=50),
        ),
        migrations.AddField(
            model_name='processlog',
            name='job_type',
            field=models.CharField(default='Stored_Proc', max_length=25),
        ),
        migrations.AddField(
            model_name='processlog',
            name='object_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='processlog',
            name='process_id',
            field=models.IntegerField(default=1),
        ),
    ]
