# Generated by Django 2.1.1 on 2019-08-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0064_processlog_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
