# Generated by Django 2.1.1 on 2019-08-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0065_processlog_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='status',
            field=models.CharField(blank=True, default='S', max_length=1),
        ),
    ]
