# Generated by Django 2.1.1 on 2019-08-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0066_processlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
