# Generated by Django 2.1.1 on 2019-08-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0067_auto_20190828_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processlog',
            name='jobflowname',
        ),
        migrations.AddField(
            model_name='processlog',
            name='jobflowdetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Jobflowdetail'),
        ),
    ]
