# Generated by Django 2.1.1 on 2019-08-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0068_auto_20190829_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='jobflowname',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meta.Jobflow'),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='jobflowdetail',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meta.Jobflowdetail'),
        ),
    ]
