# Generated by Django 2.1.1 on 2019-08-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0069_auto_20190830_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processlog',
            name='jobflowdetail',
        ),
        migrations.RemoveField(
            model_name='processlog',
            name='jobflowname',
        ),
        migrations.RemoveField(
            model_name='processlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Processlog',
        ),
    ]
