# Generated by Django 2.1.1 on 2019-08-30 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meta', '0070_auto_20190830_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_job_name', models.CharField(default='job_name_alias_name', max_length=50)),
                ('process_id', models.IntegerField(default=1)),
                ('job_name', models.CharField(default='job_name', max_length=50)),
                ('job_type', models.CharField(default='Stored_Proc', max_length=25)),
                ('object_id', models.IntegerField(default=1)),
                ('additional_param', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(blank=True, default='S', max_length=1)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(auto_now=True, null=True)),
                ('jobflowdetail', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meta.Jobflowdetail')),
                ('jobflowname', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='meta.Jobflow')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
