# Generated by Django 2.1.1 on 2019-09-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0071_processlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobflow',
            options={'ordering': ['jobflowname']},
        ),
        migrations.AlterModelOptions(
            name='jobflowdetail',
            options={'ordering': ['job_name']},
        ),
    ]
