# Generated by Django 2.1.1 on 2019-09-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0077_processlog_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processlog',
            name='project_name',
        ),
    ]
