# Generated by Django 2.1.1 on 2019-09-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0078_remove_processlog_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='status',
            field=models.CharField(blank=True, default='Success', max_length=10),
        ),
    ]
