# Generated by Django 2.1.1 on 2019-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0079_auto_20190909_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='logfile',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
