# Generated by Django 2.1.1 on 2019-11-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0080_processlog_logfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processlog',
            options={'ordering': ('process_id', 'status')},
        ),
        migrations.AddField(
            model_name='processlog',
            name='log_url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
