# Generated by Django 2.1.1 on 2019-11-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0081_auto_20191111_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['project_name', 'dsn_name']},
        ),
        migrations.AlterModelOptions(
            name='env_variables',
            options={'ordering': ['project_name', 'env_variable_name']},
        ),
        migrations.AlterModelOptions(
            name='processlog',
            options={'ordering': ['process_id', 'status']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_name']},
        ),
        migrations.AlterModelOptions(
            name='report_monitor',
            options={'ordering': ['report_name', 'status']},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['project_name', 'job_name', 'script_path_name']},
        ),
        migrations.AlterModelOptions(
            name='tbllist',
            options={'ordering': ['project_name', 'dsn_name', 'table_name', 'table_type']},
        ),
    ]
