# Generated by Django 2.1.1 on 2019-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0082_auto_20191112_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='pid',
            field=models.IntegerField(default=1),
        ),
    ]
