# Generated by Django 2.1.1 on 2019-12-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0085_sch_delete_cron_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sch',
            name='jobflow_job_name',
            field=models.CharField(default='Script', max_length=50),
        ),
    ]
