# Generated by Django 2.1.1 on 2019-12-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0086_sch_jobflow_job_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sch',
            old_name='jobflow_job_name',
            new_name='job_name',
        ),
    ]
