# Generated by Django 2.1.1 on 2020-05-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0087_auto_20191201_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='email_notification',
            field=models.CharField(default='arjun.kumar@kp.org', max_length=500),
        ),
    ]
