# Generated by Django 2.1.1 on 2020-05-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0088_auto_20200531_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='email_notification',
            new_name='failure_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hdfs_dir',
        ),
        migrations.AddField(
            model_name='project',
            name='success_email',
            field=models.CharField(default='arjun.kumar@kp.org', max_length=500),
        ),
    ]
