# Generated by Django 2.1.1 on 2020-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0089_auto_20200531_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='failure_email_ind',
            field=models.BooleanField(default=False),
        ),
    ]
