# Generated by Django 2.1.1 on 2020-05-31 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0091_env_variables_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='env_variables',
            options={'ordering': ['env_variable_name']},
        ),
        migrations.RemoveField(
            model_name='env_variables',
            name='project_name',
        ),
    ]
