# Generated by Django 2.1.1 on 2020-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0093_remove_jobflow_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='executed_job_names',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
