# Generated by Django 2.1.1 on 2020-06-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0093_remove_jobflow_email_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='failure_email_ind',
            new_name='failure_email_same_as_success_email',
        ),
    ]
