# Generated by Django 2.1.1 on 2020-06-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0094_auto_20200614_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='failure_email_same_as_success_email',
            new_name='failure_email_ind',
        ),
    ]
