# Generated by Django 2.1.1 on 2020-09-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0096_processlog_executed_job_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='env_variables_project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='env_variables_project',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='env_variables',
            options={'ordering': ['project_name', 'env_variable_name']},
        ),
        migrations.RemoveField(
            model_name='processlog',
            name='executed_job_names',
        ),
        migrations.RemoveField(
            model_name='project',
            name='failure_email',
        ),
        migrations.RemoveField(
            model_name='project',
            name='failure_email_ind',
        ),
        migrations.RemoveField(
            model_name='project',
            name='success_email',
        ),
        migrations.AddField(
            model_name='env_variables',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meta.Project'),
        ),
        migrations.AddField(
            model_name='jobflow',
            name='email_notification',
            field=models.CharField(default='arjun.kumar@kp.org', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='email_notification',
            field=models.CharField(default='arjun.kumar@kp.org', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='hdfs_dir',
            field=models.CharField(default='/home/rawdata/', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Env_variables_project',
        ),
    ]
