# Generated by Django 2.1.1 on 2020-09-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0097_auto_20200914_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email_notification',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hdfs_dir',
        ),
        migrations.AddField(
            model_name='project',
            name='failure_email',
            field=models.CharField(default='arjun.kumar@kp.org', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='failure_email_ind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='success_email',
            field=models.CharField(default='arjun.kumar@kp.org', max_length=500),
        ),
    ]
