# Generated by Django 2.1.1 on 2020-09-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0098_auto_20200915_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobflow',
            name='email_notification',
        ),
    ]
