# Generated by Django 2.1.1 on 2020-09-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0099_remove_jobflow_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='executed_job_names',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sch',
            name='failure_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sch',
            name='sla_long_running_job',
            field=models.IntegerField(default=0),
        ),
    ]
