# Generated by Django 2.1.1 on 2020-09-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0100_auto_20200915_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='env_variables',
            options={'ordering': ['env_variable_name']},
        ),
    ]
