# Generated by Django 2.1.1 on 2020-09-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0102_env_variables_project'),
        ('meta', '0095_auto_20200626_1923'),
    ]

    operations = [
    ]
