# Generated by Django 2.1.1 on 2020-10-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0103_merge_20200916_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='execution_type',
            field=models.CharField(default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='db_param',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='db_port_no',
            field=models.IntegerField(default=3306),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='executed_job_names',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='project_access',
            name='notes',
            field=models.CharField(default='Need access to the project to make change and execute jobs', max_length=500),
        ),
        migrations.AlterField(
            model_name='sch',
            name='etl_sch_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='script',
            name='additional_param',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_path_name',
            field=models.CharField(max_length=500),
        ),
    ]
